---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(knitr.duplicate.label = TRUE)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(jpndistrict)

df_h17to27_pops <- 
  readr::read_rds(here::here("data-raw", "population_h17-h22.rds"))

sf_pref08 <- 
  jpn_pref(8, district = TRUE)
  
df_pref08_pops <- 
  df_h17to27_pops %>% 
  filter(pref_code == "08", year == 2015, city_type != "a") %>% 
  select(city_code, population)

sf_pref08_pops2015 <- 
  sf_pref08 %>% 
  inner_join(df_pref08_pops, 
             by = c("city_code"))
pops <- 
  c(sf_pref08_pops2015$population)

library(spdep)
# NS
moran.test(pops,
           st_coordinates(st_centroid(sf_pref08_pops2015)) %>% 
             tri2nb() %>% 
             nb2listw()) %>% 
  broom::tidy()
# NS
geary.test(pops,
           st_coordinates(st_centroid(sf_pref08_pops2015)) %>% 
             tri2nb() %>% 
             nb2listw())

```

